
CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name VARCHAR(100) NOT NULL,
    description TEXT,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    priority INT NOT NULL,
    date_creation TIMESTAMP NOT NULL,
    date_update TIMESTAMP
);