
CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name VARCHAR(100) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    date_creation TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL,
    task_list_id BIGINT,
    CONSTRAINT fk_users FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_task_lists FOREIGN KEY (task_list_id) REFERENCES task_lists(id)
);

/*CREATE INDEX idx_tasks_user ON tasks(user_id);
CREATE INDEX idx_tasks_list ON tasks(task_list_id) WHERE task_list_id IS NOT NULL;
CREATE INDEX idx_tasks_status ON tasks(status);
CREATE INDEX idx_tasks_priority ON tasks(priority);*/